<?php
/**
 * Created by PhpStorm.
 * User: pavel
 * Date: 01.10.18
 * Time: 12:09
 */

namespace app\controllers;

use app\actions\TestUserCreateAction;
use app\models\User;
use yii\rest\ActiveController;

class TestUserController extends ActiveController
{
    public $modelClass = User::class;

    /**
     * @return array
     */
    public function actions()
    {
        $actions = parent::actions();

        $actions['create'] = [
            'class' => TestUserCreateAction::class,
            'modelClass' => $this->modelClass,
            'checkAccess' => [$this, 'checkAccess'],
        ];

        return $actions; // TODO: Change the autogenerated stub
    }
}
